language: dart
sudo: false
dart:
  - dev
# TODO(devoncarew): Restore this once 1.13 goes stable.
#  - stable
script:
  - (cd dart; ./tool/travis.sh)
  - (cd java; ant -f build.xml)

branches:
  only:
    - master
