name: vm_service_lib
description: A library to access the VM Service API.
version: 0.1.0

author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_drivers

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  logging: any

dev_dependencies:
  markdown: ^0.7.0
  path: ^1.0.0
  test: ^0.12.0
