name: observatory_lib
description: A library to access the Observatory API.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  markdown: ^0.7.0

dev_dependencies:
  test: ^0.12.0
